

//population
export const LIST_POPULATIONS_REQUEST = "LIST_POPULATIONS_REQUEST";
export const LIST_POPULATIONS_SUCCESS = "LIST_POPULATIONS_SUCCESS";
export const LIST_POPULATIONS_FAILED = "LIST_POPULATIONS_FAILED";

export const LIST_POPULATIONS_MIDDLE_REQUEST =
  "LIST_POPULATIONS_MIDDLE_REQUEST";
export const LIST_POPULATIONS_MIDDLE_SUCCESS =
  "LIST_POPULATIONS_MIDDLE_SUCCESS";
export const LIST_POPULATIONS_MIDDLE_FAILED = "LIST_POPULATIONS_MIDDLE_FAILED";
//population middle
//age

export const LIST_POPULATIONS_AGE_REQUEST = "LIST_POPULATIONS_AGE_REQUEST";
export const LIST_POPULATIONS_AGE_SUCCESS = "LIST_POPULATIONS_AGE_SUCCESS";
export const LIST_POPULATIONS_AGE_FAILED = "LIST_POPULATIONS_AGE_FAILED";


//
export const LIST_POPULATIONS_FAMILY_REQUEST =
  "LIST_POPULATIONS_FAMILY_REQUEST";
export const LIST_POPULATIONS_FAMILY_SUCCESS =
  "LIST_POPULATIONS_FAMILY_SUCCESS";
export const LIST_POPULATIONS_FAMILY_FAILED = "LIST_POPULATIONS_FAMILY_FAILED";
//quali
//age

export const LIST_QUALI_REQUEST = "LIST_QUALI_REQUEST";
export const LIST_QUALI_SUCCESS = "LIST_QUALI_SUCCESS";
export const LIST_QUALI_FAILED = "LIST_QUALI_FAILED";

export const LIST_EDU_DROP_REQUEST = "LIST_EDU_DROP_REQUEST";
export const LIST_EDU_DROP_SUCCESS = "LIST_EDU_DROP_SUCCESS";
export const LIST_EDU_DROP_FAILED = "LIST_EDU_DROP_FAILED";

export const LIST_EDU_DROP_AGE_REQUEST = "LIST_EDU_DROP_AGE_REQUEST";
export const LIST_EDU_DROP_AGE_SUCCESS = "LIST_EDU_DROP_AGE_SUCCESS";
export const LIST_EDU_DROP_AGE_FAILED = "LIST_EDU_DROP_AGE_FAILED";

export const LIST_GRADE_REQUEST = "LIST_GRADE_REQUEST";
export const LIST_GRADE_SUCCESS = "LIST_GRADE_SUCCESS";
export const LIST_GRADE_FAILED = "LIST_GRADE_FAILED";

export const LIST_HOUSING_REQUEST = "LIST_HOUSING_REQUEST";
export const LIST_HOUSING_SUCCESS = "LIST_HOUSING_SUCCESS";
export const LIST_HOUSING_FAILED = "LIST_HOUSING_FAILED";

export const LIST_STATUS_REQUEST = "LIST_STATUS_REQUEST";
export const LIST_STATUS_SUCCESS = "LIST_STATUS_SUCCESS";
export const LIST_STATUS_FAILED = "LIST_STATUS_FAILED";

export const LIST_TOTAL_REQUEST = "LIST_TOTAL_REQUEST";
export const LIST_TOTAL_SUCCESS = "LIST_TOTAL_SUCCESS";
export const LIST_TOTAL_FAILED = "LIST_TOTAL_FAILED";